<?php
/**
 * Created by PhpStorm.
 * User: SunD1ng
 * Date: 17/6/26
 * Time: 下午3:03.
 */

return [
    'Actions' => 'Actions',
    'available' => 'available',
    'back_to_dpp_video' => 'Back to iVideoAdd Playlist',
    'back_to_manage_scenes' => 'Back To Manage Scenes',
    'dpp_duration' => 'iVideoAdd Duration',
    'dpp_playlist' => 'iVideoAdd Playlist — :name',
    'dpp_requests' => 'iVideoAdd Requests',
    'dpp_request_new' => 'New iVideoAdd Requests',
    'dpp_request_ready' => 'Ready iVideoAdd Requests',
    'dpp_title' => 'iVideoAdd',
    'dpp_videos' => 'iVideoAdd — Videos',
    'Duration' => 'Duration',
    'edit_scene' => 'Edit Scene',
    'manage_scenes' => 'Manage Scenes — ',
    'new_dpp_request' => 'New iVideoAdd Requests',
    'note_before_publish' => '<strong>Note:</strong> Please fill in the details for all scenes before you publish.',
    'Organization' => 'Organization',
    'publish_to_cp' => 'Publish to CP',
    'publish_confirm' => 'Publish this iVideoAdd Playlist?',
    'publish_confirm_content' => '<pl>A total of <b>:number</b> new scenes are uploaded to this playlist.</p><p>Click “Publish” to confirm and publish the scenes to the Content Provider.</p>',
    'publish_incomplete' => 'Incomplete Scene Data',
    'publish_incomplete_content' => 'You have incomplete scene data in some of your scenes. Please check before you publish.',
    'Playlist' => 'Playlist',
    'ready_dpp_request' => 'Ready iVideoAdd Requests',
    'Scene' => 'Scene',
    'scenes' => 'scenes',
    'Scenes' => 'Scenes',
    'scene_detail' => 'Scene Detail',
    'scene_duration' => 'Scene Duration',
    'scene_dpp_duration' => 'iVideoAdd Duration',
    'scene_end' => 'Scene End',
    'scene_information' => 'Scene Information',
    'scene_image' => 'Scene Image',
    'scene_locale' => 'Scene Locale',
    'scene_name' => 'Scene Name',
    'scene_start' => 'Scene Start',
    'scene_type' => 'Scene Type',
    'scene_type_select' => 'Select a Scene Type',
    'scene_type_signage' => 'Signage',
    'scene_type_product' => 'Product',
    'scene_type_video' => 'Video',
    'scene_type_logo' => 'Logo',
    'seconds' => 'seconds',
    'Status' => 'Status',
    'status_all' => 'All',
    'status_filter' => 'Status Filter',
    'status_review' => 'Review',
    'status_processing' => 'Processing',
    'status_pending' => 'Pending',
    'status_published' => 'Published',
    'submitted_at' => 'Submitted At',
    'summary' => 'iVideoAdd Summary',
    'summary_total_video' => 'Total Video Analyzed',
    'summary_total_videos' => ':videos Videos',
    'summary_total_scene' => 'Total Scene Detected',
    'summary_total_scenes' => ':scenes Scenes',
    'summary_total_valuation' => 'Total iVideoAdd Valuation',
    'summary_total_valuations' => ':seconds Seconds',
    'summary_total_duration' => 'Total iVideoAdd Duration',
    'summary_total_durations' => ':seconds Seconds',
    'Title' => 'Title',
    'total_scenes_uploaded' => 'Total :scenes scenes uploaded',
    'update_success' => 'Scene is updated successfully.',
    'delete_success' => 'Success! Scene is deleted.',
    'Videos' => 'Videos',
    'upload_a_file' => 'Upload a file',
    'processing_dropped_files' => 'Processing dropped files...',
    'supported_format' => 'Supported format',

    'descriptions' => 'Descriptions',
    'delete_confirm' => 'This action is not reversible. Do you want to proceed?',
    'delete_playlist' => 'Delete Playlist',
    'last_updated' => 'Last Updated',
    'not_available' => 'N/A',
    'scenes_management' => 'Scenes Management',
    'total_scenes' => 'Total Scenes',
    'total_scenes_available' => 'Total :scenes scenes available',
    'total_dpp_time' => 'Total iVideoAdd Time',
    'type' => 'Type :type',
    'type_all' => 'All ',
    'type_filter' => 'Type Filter',
    'type_signage' => 'Signage',
    'type_product' => 'Product',
    'type_video' => 'Video',
    'type_logo' => 'Logo',
    'valuation_analysis' => 'Valuation Analysis',

    'close' => 'close',
    'created_failed' => 'Dpp scene is created failed.',
    'upload_failed' => 'Dpp scene picture upload failed',
    'upload_tips' => 'Drop files here or click to upload',
];
