<?php

return [
    'subscriptions' => 'Feeds',
    'add_subscription' => 'Add Feed',
    'add_subscriptions' => 'Add Feeds',
    'update_subscription' => 'Edit Feed',
    'i_cat_id' => 'Import Category ID',
    'p_category' => 'Post Category',
    'i_cat_name' => 'Import Category Name',
    'p_type' => 'Post Type',
    'p_status' => 'Post Status',
    'post' => 'Post',
    'private' => 'Private',
    'draft' => 'Draft',
    'reset' => 'Reset',
    'error1' => 'Oops!',
    'msg_error1' => 'Something is not right with your submission. Please check the form for more details.',
    'msg_error2' => 'Something is not right with your submission.',
    'success1' => 'Nice!',
    'msg_subscribed' => 'A new syndication is added and ready for duty.',
    'msg_subscribe_already' => 'Selected feed is already added.',
    'msg_error_field' => 'Selected value is wrong.',
    'msg_successfully_saved' => 'Successfully saved your changes.',
    'msg_successfully_deleted' => 'Successfully deleted.',
    'msg_delete_fail' => 'Could not delete.',
    'bulk' => 'Bulk Action',
    'unsubscribe' => 'Delete',
    'apply' => 'Apply',
    'select_cat' => 'Select a Category',
    'back' => 'Go Back',
    'confirm_delete' => 'Are you sure you want to delete?',
    'manage_p_subscriptions' => 'Manage Post Subscriptions',
];
