<?php
/**
 * Created by PhpStorm.
 * User: SunD1ng
 * Date: 17/6/26
 * Time: 下午3:03.
 */

return [
    'Actions' => '操作',
    'available' => '有效',
    'back_to_dpp_video' => '返回到DPP列表',
    'back_to_manage_scenes' => '返回到场景管理',
    'dpp_duration' => 'DPP时长',
    'dpp_playlist' => 'DPP列表 — :名称',
    'dpp_requests' => 'DPP请求',
    'dpp_request_new' => '新的DPP请求',
    'dpp_request_ready' => '就绪 DPP请求',
    'dpp_title' => 'DPP名称',
    'dpp_videos' => 'DPP — 视频',
    'Duration' => '时长',
    'edit_scene' => '编辑场景',
    'manage_scenes' => '管理场景 — ',
    'new_dpp_request' => '新的DPP请求',
    'note_before_publish' => '<strong>注意:</strong> 在公开前请填写所有场景的详细信息',
    'Organization' => '组织机构',
    'publish_to_cp' => '发布予CP',
    'publish_confirm' => '发布此DPP列表?',
    'publish_confirm_content' => '<pl>公 <b>:number</b> 个新场景上传到此列表</p><p>点击 “发布” 以发布给媒资提供方</p>',
    'publish_incomplete' => '场景数据不完整',
    'publish_incomplete_content' => '你的场景信息不完整，请在发布前检查场景信息',
    'Playlist' => '列表',
    'ready_dpp_request' => '就绪 DPP请求',
    'Scene' => '场景',
    'scenes' => '场景',
    'Scenes' => '场景',
    'scene_detail' => '场景详情',
    'scene_duration' => '场景时长',
    'scene_dpp_duration' => 'DPP时长',
    'scene_end' => '场景结束',
    'scene_information' => '场景信息',
    'scene_image' => '场景图片',
    'scene_locale' => '场景拍摄地',
    'scene_name' => '场景名称',
    'scene_start' => '场景开始',
    'scene_type' => '场景类型',
    'scene_type_select' => '选择一个场景类型',
    'scene_type_signage' => '引导标识',
    'scene_type_product' => '商品',
    'scene_type_video' => '视频',
    'scene_type_logo' => '表示',
    'seconds' => '秒',
    'Status' => '状态',
    'status_all' => '所有',
    'status_filter' => '状态筛选',
    'status_review' => '查看',
    'status_processing' => '处理中',
    'status_pending' => '待定',
    'status_published' => '已发布',
    'submitted_at' => '提交于',
    'summary' => 'DPP总览',
    'summary_total_video' => '所有分析视频',
    'summary_total_videos' => ':videos 视频',
    'summary_total_scene' => '所有检测到的场景',
    'summary_total_scenes' => ':scenes 场景',
    'summary_total_valuation' => '所有DPP估值',
    'summary_total_valuations' => ':seconds 秒',
    'summary_total_duration' => '所有DPP市场',
    'summary_total_durations' => ':seconds 秒',
    'Title' => '标题',
    'total_scenes_uploaded' => '共上传 :scenes 场景',
    'update_success' => '场景成功更新',
    'delete_success' => '成功!场景已移除',
    'Videos' => '视频',
    'upload_a_file' => '上传文件',
    'processing_dropped_files' => '处理上传文件中...',
    'supported_format' => '支持格式',

    'descriptions' => '描述',
    'delete_confirm' => '此操作不可撤销，你是否仍要继续执行？',
    'delete_playlist' => '删除列表',
    'last_updated' => '最新更新',
    'not_available' => 'N/A',
    'scenes_management' => '场景管理',
    'total_scenes' => '所有场景',
    'total_scenes_available' => '共 :scenes 有效场景',
    'total_dpp_time' => '所有DPP时间',
    'type' => '类型 :type',
    'type_all' => '所有 ',
    'type_filter' => '类型筛选',
    'type_signage' => '引导标识',
    'type_product' => '商品',
    'type_video' => '视频',
    'type_logo' => '标识',
    'valuation_analysis' => '估值分析',

    'close' => '关闭',
    'created_failed' => 'Dpp场景生成失败',
    'upload_failed' => 'Dpp场景图片上传失败',
    'upload_tips' => '将文件拖至此处或点击上传',
];
