<?php

return [
    'subscriptions' => '媒体源',
    'add_subscription' => '添加媒体源',
    'add_subscriptions' => '添加媒体源',
    'update_subscription' => '编辑媒体源',
    'i_cat_id' => '导入分类 ID',
    'p_category' => '文稿分类',
    'i_cat_name' => '导入分类名称',
    'p_type' => '文稿类别',
    'p_status' => '文稿状态',
    'post' => '发布',
    'private' => '私享',
    'draft' => '草稿',
    'reset' => '重置',
    'error1' => '糟糕!',
    'msg_error1' => '您的提交有问题，请查看表格获取更多信息',
    'msg_error2' => '您的提交有问题',
    'success1' => '成功!',
    'msg_subscribed' => '一个新的同步已经添加并且可以使用',
    'msg_subscribe_already' => '所选媒体源已存在',
    'msg_error_field' => '所选内容错误',
    'msg_successfully_saved' => '您的修改已成功',
    'msg_successfully_deleted' => '删除成功',
    'msg_delete_fail' => '无法删除',
    'bulk' => '批量操作',
    'unsubscribe' => '删除',
    'apply' => '应用',
    'select_cat' => '选择分类',
    'back' => '返回',
    'confirm_delete' => '确定删除?',
    'manage_p_subscriptions' => '管理文稿订阅',
];
