<?php

return [
    'back_to_compare' => 'Back To Video Compare',
    'compare_videos' => 'Compare Videos',
    'duration' => 'Duration',
    'failed' => 'Failed',
    'finished' => 'Finished',
    'fragment' => 'Fragment',
    'match_count' => 'Match Count',
    'match_result_analysis' => 'Match Result Statist',
    'match_video_start_position' => 'match video start position',
    'max_confidence' => 'Max Similarity',
    'max_match_duration' => 'Max Match Duration',
    'name' => 'Name',
    'no_videos' => 'No found video compare details',
    'no_video_compare' => 'No found video compare datas',
    'new_video_compare' => 'New Video Compare',
    'processing' => 'Processing',
    'search_video_start_position' => 'Search video start position',
    'second' => 'Second',
    'showing_from_to_video_compare' => 'Showing :from to :to of :total video compare requests',
    'showing_from_to_videos' => 'Showing :from to :to of :total videos',
    'similar_situation' => 'Similar Situation',
    'similar_original' => 'original',
    'similar_scaled_up' => 'scaled up',
    'similar_scaled_down' => 'scaled down',
    'similar_cropped' => 'cropped',
    'similar_padded' => 'padded',
    'similarity' => 'Similarity',
    'single_video_max_match_fragment' => 'Single Video Max Match Fragment',
    'status_filter' => 'Status Filter',
    'submitted_at' => 'Submitted At',
    'summary' => 'Summary Of Compare Result',
    'summary_total_match_duration' => 'All Match Duration',
    'summary_total_match_fragment' => 'All Matched Fragments',
    'summary_total_match_video' => 'All Match Videos',
    'summary_total_video' => 'All Compare Videos',
    'total_duration' => 'Duration',
    'video' => 'Video',
    'video_compare' => 'Video Compare',
    'video_compare_result' => 'Video Compare Result - :name',
    'video_compare_request_submitted_success' => 'Video compare request has submitted success',
    'video_compare_request_submitted_failed' => 'Video compare request submitted failed',
    'video_duration' => 'Duration',
    'video_name' => 'Video Name',
    'view' => 'View',
];
