<?php
/**
 * User: Stone
 * Date: 19/1/18.
 */

return [
    'back_to_dpp_playlist' => '返回到DPP列表',
    'back_to_dpp_video' => '返回到DPP视频',
    'descriptions' => '描述',
    'dpp_duration' => 'DPP时长',
    'dpp_video' => 'DPP视频 — :名称',
    'duration' => '时长',
    'ivideoadd_summary' => '产品植入总览',
    'keywords_hint' => '使用逗号来添加多个关键词',
    'locale' => '拍摄场景',
    'name' => '名字',
    'no_locales' => '无拍摄场景',
    'not_available' => 'N/A',
    'scene_blacklist' => 'Blacklisted Verticals',
    'scene_configuration' => '场景结构',
    'scene_duration' => '场景时长',
    'scene_end' => '场景结束',
    'scene_image' => '场景图片',
    'scene_information' => '场景信息',
    'scene_locale' => '场景拍摄地',
    'scene_locales_analysis' => '拍摄场景分析',
    'scene_locales_analyzed_results' => '拍摄场景分析结果',
    'scene_name' => '场景 — :name',
    'scene_start' => '场景开始',
    'scene_suitable' => 'Suitable Verticals',
    'scene_type_logo' => '标识',
    'scene_type_product' => '商品',
    'scene_type_signage' => '引导标识',
    'scene_type_video' => '视频',
    'scene_type' => '场景类型',
    'scene_type' => '场景类型',
    'scene' => '场景',
    'scenes_management' => '场景管理',
    'scenes_small' => '场景',
    'seconds' => '秒数',
    'showing_from_to_locales' => '显示 :从 :到 :共 场景',
    'single_summary' => '总览',
    'summary_scene_locales_analyzed' => '场景拍摄分析总览',
    'summary_total_duration' => '总DPP时长',
    'summary_total_durations' => ':seconds 秒',
    'summary_total_scene' => '总场景数量',
    'summary_total_scenes' => ':scenes 场景',
    'summary_total_valuation' => '总DPP估价',
    'total_dpp_duration' => '总DPP时长',
    'total_dpp_time' => '总DPP时间',
    'total_duration' => '总时长',
    'total_scenes_available' => '总 :scenes 有效场景',
    'total_scenes' => '所有场景',
    'type_all' => '所有 ',
    'type_filter' => '类型筛选',
    'type_logo' => '标识',
    'type_product' => '产品',
    'type_signage' => '引导标识',
    'type_video' => '视频',
    'type' => '类型',
    'unit_scene' => '场景',
    'valuation_analysis' => '估值分析',
];
