<?php
/**
 * Stone
 * 22/1/19.
 */

return [
    'action_is_not_reversible' => '此操作不可撤销，是否继续？',
    'ai_label_logo' => '特殊标识',
    'ai_label_normal' => '正常',
    'ai_label_others' => '其它暴恐渉政',
    'ai_label_outfit' => '特殊装束',
    'ai_label_politics' => '渉政',
    'ai_label_porn' => '色情',
    'ai_label_sexy' => '性感',
    'ai_label_terrorism' => '暴恐',
    'ai_label_weapon' => '武器',
    'ai_result_block' => '违规',
    'ai_result_pass' => '通过',
    'ai_result_review' => '疑似',
    'album' => '专辑',
    'all_page' => '所有页面',
    'approve' => '同意',
    'artist' => '作者',
    'back_to_request_logs' => '回到请求通知',
    'block' => '违规',
    'bulk_ai_review' => '批量AI审核',
    'bulk_ai_review_request_logs' => '批量AI审核请求通知',
    'bulk_approve' => '批量同意',
    'bulk_approve_request_logs' => '批量同意请求通知',
    'bulk_reject' => '批量回绝',
    'bulk_reject_request_logs' => '批量回绝请求通知',
    'current_page' => '当前页面',
    'descriptions' => '描述',
    'fail' => '审核失败',
    'featured_image' => '封面图',
    'generate_terms' => '生成分销条款',
    'genre' => '类别',
    'have_chosen' => '已选择',
    'language' => '语言',
    'msg_comment_successfully' => '添加修改意见成功',
    'msg_comment_unsuccessfully' => '添加修改意见失败',
    'no_enabled' => '未开启',
    'no_record_selected' => '未选择任何记录',
    'no_request_logs' => '无请求通知',
    'pass' => '通过',
    'processing' => '审核中',
    'reject' => '回绝',
    'released_at' => '发布于',
    'request_logs_are_bulk_approved' => '请求通知已批量同意',
    'request_logs_are_bulk_rejected' => '请求通知已批量回绝',
    'request_logs' => '请求通知',
    'review' => '疑似',
    'showing_from_to_request_logs' => '显示 :from 到 :to 共有 :total 请求通知',
    'showing_from_to_ai_review_results' => '显示 :from 到 :to 共有 :total 条AI审核视频结果',
    'tags' => '标签',
    'video_information' => '视频信息',
    'video_metadata' => '视频源信息',
    'video_type' => '视频类型',
    'year' => '年份',
];
