<?php
/**
 * Stone
 * 22/1/19.
 */

return [
    'action_is_not_reversible' => 'This action is not reversible. Do you want to proceed?',
    'ai_label_logo' => 'Logo',
    'ai_label_normal' => 'Normal',
    'ai_label_others' => 'Others',
    'ai_label_outfit' => 'Outfit',
    'ai_label_politics' => 'Politics',
    'ai_label_porn' => 'Porn',
    'ai_label_sexy' => 'Sexy',
    'ai_label_terrorism' => 'Terrorism',
    'ai_label_weapon' => 'Weapon',
    'ai_result_block' => 'Block',
    'ai_result_pass' => 'Pass',
    'ai_result_review' => 'Review',
    'album' => 'Album',
    'all_page' => 'All Page',
    'approve' => 'Approve',
    'artist' => 'Artist',
    'back_to_request_logs' => 'Back To Request Logs',
    'block' => 'Block',
    'bulk_ai_review' => 'Bulk AI Review',
    'bulk_ai_review_request_logs' => 'Bulk AI Review Request Logs',
    'bulk_approve' => 'Bulk Approve',
    'bulk_approve_request_logs' => 'Bulk Approve Request Logs',
    'bulk_reject' => 'Bulk Reject',
    'bulk_reject_request_logs' => 'Bulk Reject Request Logs',
    'current_page' => 'Current Page',
    'descriptions' => 'Descriptions',
    'fail' => 'Fail',
    'featured_image' => 'Featured Image',
    'generate_terms' => 'Generate Terms',
    'genre' => 'Genre',
    'have_chosen' => 'Have Chosen',
    'language' => 'Language',
    'msg_comment_successfully' => 'save comment successfully',
    'msg_comment_unsuccessfully' => 'save comment unsuccessfully',
    'no_enabled' => 'No Enabled',
    'no_record_selected' => 'No Record Selected',
    'no_request_logs' => 'No Request Logs',
    'pass' => 'Pass',
    'processing' => 'Processing',
    'reject' => 'Reject',
    'released_at' => 'Released At',
    'request_logs_are_bulk_approved' => 'Request Logs Approved',
    'request_logs_are_bulk_rejected' => 'Request Logs Rejected',
    'request_logs' => 'Request Logs',
    'review' => 'Review',
    'showing_from_to_request_logs' => 'Showing :from to :to of :total request logs',
    'showing_from_to_ai_review_results' => 'Showing :from to :to of :total AI review video results',
    'tags' => 'Tags',
    'video_information' => 'Video Information',
    'video_metadata' => 'Video Metadata',
    'video_type' => 'Video Type',
    'year' => 'Year',
];
