<?php
/**
 * User: Stone
 * Date: 19/1/18.
 */

return [
    'back_to_dpp_playlist' => 'Back To iVideoAdd Playlist',
    'back_to_dpp_video' => 'Back To iVideoAdd Video',
    'descriptions' => 'Descriptions',
    'dpp_duration' => 'iVideoAdd Duration',
    'dpp_video' => 'iVideoAdd Video — :name',
    'duration' => 'Duration',
    'ivideoadd_summary' => 'iVideoAdd Summary',
    'keywords_hint' => 'Separate keywords with commas',
    'name' => 'Name',
    'no_locales' => 'No locales',
    'not_available' => 'N/A',
    'scene_blacklist' => 'Blacklisted Verticals',
    'scene_configuration' => 'Scene Configuration',
    'scene_duration' => 'Scene Duration',
    'scene_end' => 'Scene End',
    'scene_image' => 'Scene Image',
    'scene_information' => 'Scene Information',
    'scene_locale' => 'Scene Locale',
    'scene_locales_analysis' => 'Scene Locales Analysis',
    'scene_locales_analyzed_results' => 'Scene Locales Analyzed Results',
    'scene_name' => 'Scene — :name',
    'scene_start' => 'Scene Start',
    'scene_suitable' => 'Suitable Verticals',
    'scene_type_logo' => 'Logo',
    'scene_type_product' => 'Product',
    'scene_type_signage' => 'Signage',
    'scene_type_video' => 'Video',
    'scene_type' => 'Scene Type',
    'scene_type' => 'Scene Type',
    'scene' => 'Scene',
    'scenes_management' => 'Scenes Management',
    'scenes_small' => 'scenes',
    'seconds' => 'seconds',
    'showing_from_to_locales' => 'Showing :from to :to of :total locales',
    'single_summary' => 'Summary',
    'summary_scene_locales_analyzed' => 'Summary of Scene Locales Analyzed',
    'summary_total_duration' => 'Total iVideoAdd Duration',
    'summary_total_durations' => ':seconds Seconds',
    'summary_total_scene' => 'Total Scene Detected',
    'summary_total_scenes' => ':scenes Scenes',
    'summary_total_valuation' => 'Total iVideoAdd Valuation',
    'total_dpp_duration' => 'Total iVideoAdd Duration',
    'total_dpp_time' => 'Total iVideoAdd Time',
    'total_duration' => 'Total Duration',
    'total_scenes_available' => 'Total :scenes scenes available',
    'total_scenes' => 'Total Scenes',
    'type_all' => 'All ',
    'type_filter' => 'Type Filter',
    'type_logo' => 'Logo',
    'type_product' => 'Product',
    'type_signage' => 'Signage',
    'type_video' => 'Video',
    'type' => 'Type',
    'unit_scene' => 'scene(s)',
    'valuation_analysis' => 'Valuation Analysis',
];
