<?php

return [
    //signup page
    'register_account' => '注册账户',
    'organization_name' => '组织机构名称',
    'organization_address' => '组织机构地址',
    'organization_country' => '组织机构所属国家',
    'email_address' => '邮箱地址',
    'password' => '密码',
    'i_agree_to_the_terms_and_conditions' => '本人同意相应条款与要求',
    'register' => '注册',
    'already_have_an_account' => '已经有一个账户了?',
    'login' => '登录',
    'oops' => '糟糕!',
    'error' => '您的提交有误',
    'success' => '成功!',
    'get_email' => '密码已发送至您的邮箱，请查收',
    'invalid_token' => '无效激活码，请联系管理员获取更多信息',
    'well_done' => '一切顺利!',
    'successful_activate' => '您已成功激活您的账户',
    'account_login' => '账户登录',
    'remember_me' => '记住密码',
    'forgotten_password' => '忘记密码',
    'email' => '邮箱地址',
    'password' => '密码',
    'ivideo' => 'iVideoExchange',
    'account_registration' => '账户注册',
    'ivideo_marketplace_requires_an_active_account' => 'CNC全球短视频聚合分发平台需要一个活跃账户才能进入.',
    'for_more_information' => '更多的信息请联系管理人员',
    'user' => '新华用户',
    'register_success' => '注册成功',
    'no_user_right' => '您的帐户没有设置任何权限，无法登录.',
];
