<?php

return [
    'actions' => 'Actions',
    'active' => 'Active',
    'address' => 'Address',
    'api' => 'API',
    'back' => 'Back',
    'continue' => 'Continue',
    'confirm_delete' => 'Are you sure you want to delete?',
    'content' => 'Content',
    'copy' => 'Copy',
    'country' => 'Country',
    'created_at' => 'Created At',
    'date' => 'Date',
    'delete' => 'Delete',
    'disable' => 'Disable',
    'edit' => 'Edit',
    'email' => 'Email',
    'gb' => 'GB',
    'home' => 'Home',
    'id' => 'ID',
    'inactive' => 'Inactive',
    'keywords' => 'Keywords',
    'level' => 'Level',
    'login' => 'Login',
    'name' => 'Name',
    'new' => 'New',
    'nice' => 'Nice!',
    'oops' => 'Oops!',
    'organization' => 'Organization',
    'password' => 'Password',
    'role' => 'Role',
    'save' => 'Save',
    'search' => 'Search',
    'status' => 'Status',
    'submit_error' => 'There is an error with your submission.',
    'type' => 'Type',
    'update' => 'Update',
    'well_done' => 'Well done!',
];
