<?php

return [
    'back_to_compare' => '返回视频对比',
    'compare_videos' => '对比视频详情',
    'duration' => '时长',
    'failed' => '失败',
    'finished' => '已完成',
    'fragment' => '片段',
    'match_count' => '匹配个数',
    'match_result_analysis' => '匹配结果统计',
    'match_video_start_position' => '比对视频起点',
    'max_confidence' => '最大相似度',
    'max_match_duration' => '最大匹配时长',
    'name' => '名称',
    'no_videos' => '没有视频对比详情',
    'no_video_compare' => '没有视频对比列表数据',
    'new_video_compare' => '新建视频对比',
    'processing' => '正在对比',
    'search_video_start_position' => '此视频起点',
    'second' => '秒',
    'showing_from_to_video_compare' => '显示 :from 到 :to 共有 :total 个视频对比',
    'showing_from_to_videos' => '显示 :from 到 :to 共有 :total 个视频',
    'similar_situation' => '相似情况',
    'similar_original' => '基本一致',
    'similar_scaled_up' => '分辨率高',
    'similar_scaled_down' => '分辨率低',
    'similar_cropped' => '裁剪',
    'similar_padded' => '加边框',
    'similarity' => '相似度',
    'single_video_max_match_fragment' => '单个视频最大匹配片段',
    'status_filter' => '状态筛选',
    'submitted_at' => '提交时间',
    'summary' => '对比结果总览',
    'summary_total_match_duration' => '所有匹配时长',
    'summary_total_match_fragment' => '所有检测到的匹配片段',
    'summary_total_match_video' => '所有匹配视频',
    'summary_total_video' => '所有检测视频',
    'total_duration' => '总时长',
    'video' => '视频',
    'video_compare' => '视频对比',
    'video_compare_result' => '视频对比结果 - :name',
    'video_compare_request_submitted_success' => '已成功提交视频对比请求',
    'video_compare_request_submitted_failed' => '视频对比请求提交失败',
    'video_duration' => '视频时长',
    'video_name' => '视频名称',
    'view' => '查看',
];
