<?php

return [
    'allowed_regions' => '允许区域',
    'availability_period' => '有效期间',
    'available_now' => '现在有效',
    'business_terms' => '商业条款',
    'country_of_origin' => '内容原国家',
    'default_footnote' => '收益分成和授权费模式待商讨',
    'except' => '排除',
    'exclusive' => '独家',
    'exclusive_property' => '独家内容',
    'footnote' => '注释',
    'forever' => '永久',
    'last_updated' => '最后更新时间',
    'license_fee' => '授权费',
    'minimum_guarantee' => '保底费用',
    'non_exclusive' => '非独家',
    'not_specified' => '未指定',
    'platforms' => '播放平台',
    'playlist_details' => '内容列表详情',
    'playlist_information' => '内容列表信息',
    'playlist_videos' => '内容列表视频',
    'regional_rights' => '区域权利',
    'request_for_content' => '请求内容',
    'revenue_share' => '收益分成',
    'supported_distribution' => '支持的分销模式',
    'supported_models' => '支持的模式',
    'terms_of_distribution' => '分发条款',
    'show' => '显示',
    'to' => '到',
    'of' => '共',
    'entries' => '视频',
];
