<?php

return [
    'allowed_regions' => 'Allowed Regions',
    'availability_period' => 'Availability Period',
    'available_now' => 'Available Now',
    'business_terms' => 'Business Terms',
    'country_of_origin' => 'Country of Origin',
    'default_footnote' => 'Revenue Share and Licensing Fees are to be discussed.',
    'except' => 'Except',
    'exclusive' => 'Exclusive',
    'exclusive_property' => 'Exclusive Property',
    'footnote' => 'Footnote',
    'forever' => 'Forever',
    'last_updated' => 'Last Updated',
    'license_fee' => 'License Fee',
    'minimum_guarantee' => 'Minimum Guarantee',
    'non_exclusive' => 'Non-exclusive',
    'not_specified' => 'Not specified',
    'platforms' => 'Platforms',
    'playlist_details' => 'Playlist Details',
    'playlist_information' => 'Playlist Information',
    'playlist_videos' => 'Playlist Videos',
    'regional_rights' => 'Regional Rights',
    'request_for_content' => 'Request For Content',
    'revenue_share' => 'Revenue Share',
    'supported_distribution' => 'Supported Distribution',
    'supported_models' => 'Supported Models',
    'terms_of_distribution' => 'Terms of Distribution',
    'show' => 'show',
    'to' => 'to',
    'of' => 'of',
    'entries' => 'entries',
];
