<?php

return [
    'actions' => '操作',
    'active' => '已激活',
    'address' => '地址',
    'api' => 'API',
    'back' => '返回',
    'continue' => '继续',
    'confirm_delete' => '你确定要删除吗？',
    'content' => '内容',
    'copy' => '复制',
    'country' => '国家',
    'created_at' => '创建于',
    'date' => '日期',
    'delete' => '删除',
    'disable' => '已禁用',
    'edit' => '编辑',
    'email' => '邮箱',
    'gb' => 'GB',
    'home' => '首页',
    'id' => 'ID',
    'inactive' => '未激活',
    'keywords' => '关键词',
    'level' => '级别',
    'login' => '登录',
    'name' => '名称',
    'new' => '新建',
    'nice' => '好极了!',
    'oops' => '糟糕!',
    'organization' => '组织机构',
    'password' => '密码',
    'role' => '角色',
    'save' => '存储',
    'search' => '搜索',
    'status' => '状态',
    'submit_error' => '您提交的信息发生了错误。',
    'type' => '类别',
    'update' => '更新',
    'well_done' => '一切顺利!',
];
